# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfbf9ab10342929f96e08f2b29fcf595857611e3df2d4371278a148efed075480a4f5f7a2468d2d84f11772e2c86794ae6bd426c7c2bb2e97fe04acadd1a6245

test:
  secret_key_base: 050e57cfbefeb90291965bd2364ab2ccc296f11f0dd8a1abc05aa0e8cb95f3cf26318ae1891240af351f530d53ba973d9f8edddebdca09f15441c11ca5133c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
